"""Client reports.

**Tenancy comes from the token, and generation needs a single tenant.** There is
no `tenant_id` parameter here: a staff user switches to the client and generates
in their context. That is the same decision `/rules/{rule_id}` makes, and it also
matches how the work actually happens — you write a report *for* a client, so
being in their context is not an inconvenience.

**Two audiences, two visibilities.** Staff see drafts and issued reports and can
generate. A client user sees their own tenant's **issued** reports and nothing
else — a draft is working material, and a client discovering a half-finished
report about themselves is a bad day for everyone.

**Issuing is a one-way door.** A draft can be regenerated and re-worded; an
issued report is what the client received and is never rewritten. Getting the
numbers wrong afterwards means issuing a new one, which is exactly what a paper
process would do.
"""

import uuid
from datetime import UTC, datetime
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import aliased

from app import audit
from app.db import get_session
from app.deps.auth import CurrentUser, accessible_tenant_ids
from app.deps.tenancy import TenantScope, get_tenant_scope
from app.models import Report, Tenant, User
from app.reports import builder
from app.schemas.report import (
    ReportCreate,
    ReportPreview,
    ReportRead,
    ReportSummary,
    ReportUpdate,
)

router = APIRouter(prefix="/reports", tags=["reports"])

Session = Annotated[AsyncSession, Depends(get_session)]
Scope = Annotated[TenantScope, Depends(get_tenant_scope)]

NOT_FOUND = HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="No such report.")
NEEDS_TENANT = HTTPException(
    status_code=status.HTTP_400_BAD_REQUEST,
    detail="A report covers one client. Switch to that client first, then generate.",
)


def _is_staff(user: User) -> bool:
    return user.role in ("platform_admin", "soc_analyst")


async def _require_tenant(session: AsyncSession, scope: TenantScope) -> Tenant:
    if scope.tenant_id is None:
        raise NEEDS_TENANT
    tenant = await session.get(Tenant, scope.tenant_id)
    if tenant is None:
        raise NEEDS_TENANT
    return tenant


async def _visible(session: AsyncSession, user: User, scope: TenantScope):
    """The reports this token may read.

    Client users are narrowed to issued reports here rather than in each handler,
    so a new route cannot forget to do it.
    """
    author = aliased(User)
    stmt = (
        select(Report, Tenant, author)
        .join(Tenant, Tenant.id == Report.tenant_id)
        .join(author, author.id == Report.generated_by, isouter=True)
    )
    stmt = scope.apply(stmt, Report.tenant_id)
    if scope.is_fleet_view:
        allowed = await accessible_tenant_ids(session, user)
        if allowed is not None:
            stmt = stmt.where(Report.tenant_id.in_(allowed))
    if not _is_staff(user):
        stmt = stmt.where(Report.status == "issued")
    return stmt


def _summarise(report: Report, tenant: Tenant, author: User | None) -> ReportSummary:
    payload = ReportSummary.model_validate(report)
    payload.tenant_name = tenant.name
    payload.tenant_slug = tenant.slug
    if author is not None:
        payload.generated_by_name = author.full_name
    return payload


async def _load(
    session: AsyncSession, user: User, scope: TenantScope, report_id: uuid.UUID
) -> tuple[Report, Tenant, User | None]:
    stmt = (await _visible(session, user, scope)).where(Report.id == report_id)
    row = (await session.execute(stmt)).first()
    if row is None:
        # Identical whether it does not exist, belongs to another tenant, or is a
        # draft this caller may not see.
        raise NOT_FOUND
    return row[0], row[1], row[2]


async def _next_number(session: AsyncSession, tenant_id: uuid.UUID) -> int:
    """Per-tenant sequential. Reports are generated by a person pressing a button,
    not by an ingest path, so the contention that justified a counter row for
    incidents does not exist here."""
    current = await session.scalar(
        select(Report.number)
        .where(Report.tenant_id == tenant_id)
        .order_by(Report.number.desc())
        .limit(1)
    )
    return (current or 0) + 1


def _default_title(tenant: Tenant, period_start: datetime, period_end: datetime) -> str:
    return f"{tenant.name} — security report, {period_start:%d %b %Y} to {period_end:%d %b %Y}"


@router.get("", response_model=list[ReportSummary])
async def list_reports(
    user: CurrentUser,
    session: Session,
    scope: Scope,
    limit: Annotated[int, Query(ge=1, le=200)] = 50,
) -> list[ReportSummary]:
    stmt = (await _visible(session, user, scope)).order_by(
        Report.period_end.desc(), Report.number.desc()
    )
    rows = (await session.execute(stmt.limit(limit))).all()
    return [_summarise(report, tenant, author) for report, tenant, author in rows]


@router.post("/preview", response_model=ReportPreview)
async def preview_report(
    payload: ReportCreate, user: CurrentUser, session: Session, scope: Scope
) -> ReportPreview:
    """Compute the figures without saving them.

    Generating is cheap and saving is a commitment, so an analyst can look first.
    Nothing is written, and nothing is numbered.
    """
    if not _is_staff(user):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only AWDTECH staff generate reports.",
        )
    tenant = await _require_tenant(session, scope)
    snapshot = await builder.build(
        session,
        tenant=tenant,
        period=builder.Period(payload.period_start, payload.period_end),
        now=datetime.now(UTC),
    )
    return ReportPreview(
        period_start=payload.period_start,
        period_end=payload.period_end,
        payload=snapshot,
    )


@router.post("", response_model=ReportRead, status_code=status.HTTP_201_CREATED)
async def create_report(
    payload: ReportCreate, user: CurrentUser, session: Session, scope: Scope
) -> ReportRead:
    if not _is_staff(user):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only AWDTECH staff generate reports.",
        )
    tenant = await _require_tenant(session, scope)
    now = datetime.now(UTC)

    snapshot = await builder.build(
        session,
        tenant=tenant,
        period=builder.Period(payload.period_start, payload.period_end),
        now=now,
    )

    report = Report(
        tenant_id=tenant.id,
        number=await _next_number(session, tenant.id),
        title=payload.title
        or _default_title(tenant, payload.period_start, payload.period_end),
        status="draft",
        period_start=payload.period_start,
        period_end=payload.period_end,
        summary_note=payload.summary_note,
        payload=snapshot,
        generated_by=user.id,
        generated_at=now,
    )
    session.add(report)

    try:
        await session.flush()
    except IntegrityError as exc:
        # Two analysts generating for the same client at the same moment.
        await session.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Another report was created at the same moment. Try again.",
        ) from exc

    await audit.record(
        session,
        action="report.created",
        target_type="report",
        target_id=report.id,
        tenant_id=tenant.id,
        user_id=user.id,
        detail={
            "number": report.number,
            "period_start": payload.period_start.isoformat(),
            "period_end": payload.period_end.isoformat(),
        },
    )
    await session.commit()
    return await get_report(report.id, user, session, scope)


@router.get("/{report_id}", response_model=ReportRead)
async def get_report(
    report_id: uuid.UUID, user: CurrentUser, session: Session, scope: Scope
) -> ReportRead:
    report, tenant, author = await _load(session, user, scope, report_id)
    detail = ReportRead.model_validate(report)
    detail.tenant_name = tenant.name
    detail.tenant_slug = tenant.slug
    if author is not None:
        detail.generated_by_name = author.full_name
    return detail


@router.patch("/{report_id}", response_model=ReportRead)
async def update_report(
    report_id: uuid.UUID,
    payload: ReportUpdate,
    user: CurrentUser,
    session: Session,
    scope: Scope,
) -> ReportRead:
    """Title and covering note only, and only while a draft.

    The figures are never editable. A report whose numbers can be typed over is
    not evidence of anything.
    """
    if not _is_staff(user):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN, detail="Read-only access."
        )
    report, _tenant, _author = await _load(session, user, scope, report_id)
    if report.status == "issued":
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="This report has been issued. Generate a new one instead of "
            "rewriting what the client already received.",
        )

    changes: dict = {}
    if payload.title is not None and payload.title != report.title:
        changes["title"] = payload.title
        report.title = payload.title
    if "summary_note" in payload.model_fields_set:
        changes["summary_note"] = "set" if payload.summary_note else "cleared"
        report.summary_note = payload.summary_note

    if changes:
        await audit.record(
            session,
            action="report.updated",
            target_type="report",
            target_id=report.id,
            tenant_id=report.tenant_id,
            user_id=user.id,
            detail=changes,
        )
        await session.commit()
    return await get_report(report_id, user, session, scope)


@router.post("/{report_id}/issue", response_model=ReportRead)
async def issue_report(
    report_id: uuid.UUID, user: CurrentUser, session: Session, scope: Scope
) -> ReportRead:
    """Publish to the client. One way.

    From here the report is visible to that client's users in their own console,
    and its figures and wording are frozen.
    """
    if not _is_staff(user):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN, detail="Read-only access."
        )
    report, _tenant, _author = await _load(session, user, scope, report_id)
    if report.status == "issued":
        return await get_report(report_id, user, session, scope)

    report.status = "issued"
    report.issued_at = datetime.now(UTC)
    await audit.record(
        session,
        action="report.issued",
        target_type="report",
        target_id=report.id,
        tenant_id=report.tenant_id,
        user_id=user.id,
        detail={"number": report.number, "title": report.title},
    )
    await session.commit()
    return await get_report(report_id, user, session, scope)


@router.delete("/{report_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_report(
    report_id: uuid.UUID, user: CurrentUser, session: Session, scope: Scope
) -> None:
    """Drafts only. An issued report is a record of what a client was told."""
    if user.role != "platform_admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only a platform admin can delete a report.",
        )
    report, _tenant, _author = await _load(session, user, scope, report_id)
    if report.status == "issued":
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="An issued report is a record of what this client was told and "
            "cannot be deleted.",
        )

    await audit.record(
        session,
        action="report.deleted",
        target_type="report",
        target_id=report.id,
        tenant_id=report.tenant_id,
        user_id=user.id,
        detail={"number": report.number, "title": report.title},
    )
    await session.delete(report)
    await session.commit()
