"""Initial schema: tenants, users, alerts (partitioned), incidents, entities, audit.

Written as explicit DDL rather than autogenerated ops: native partitioning, GIN
indexes, a partial unique index, and the citext/pgcrypto extensions all sit
outside what autogenerate can express.

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute('create extension if not exists "pgcrypto"')
    op.execute('create extension if not exists "citext"')

    op.execute("""
        create table tenants (
          id            uuid primary key default gen_random_uuid(),
          slug          text not null unique,
          name          text not null,
          status        text not null default 'active'
                          check (status in ('active','suspended','offboarding')),
          ingest_secret text not null,
          ingest_cidrs  cidr[] not null default '{}',
          alert_floor   smallint not null default 7,
          grouping_window_minutes integer not null default 30,
          colour        text,
          created_at    timestamptz not null default now()
        )
    """)

    op.execute("""
        create table wazuh_connections (
          tenant_id       uuid primary key references tenants(id) on delete cascade,
          base_url        text not null,
          username        text not null,
          password_enc    bytea not null,
          key_version     integer not null default 1,
          verify_ssl      boolean not null default true,
          agent_group     text,
          last_sync_at    timestamptz,
          last_sync_error text
        )
    """)

    op.execute("""
        create table users (
          id            uuid primary key default gen_random_uuid(),
          tenant_id     uuid references tenants(id) on delete cascade,
          is_staff      boolean not null default false,
          email         citext not null unique,
          password_hash text not null,
          full_name     text not null,
          role          text not null check (role in
                          ('platform_admin','soc_analyst','client_admin','client_viewer')),
          is_active     boolean not null default true,
          last_login_at timestamptz,
          created_at    timestamptz not null default now(),
          constraint users_tenancy_check check
            ((is_staff and tenant_id is null) or (not is_staff and tenant_id is not null))
        )
    """)

    op.execute("""
        create table staff_tenant_access (
          user_id   uuid not null references users(id) on delete cascade,
          tenant_id uuid not null references tenants(id) on delete cascade,
          primary key (user_id, tenant_id)
        )
    """)

    op.execute("""
        create table agents (
          tenant_id      uuid not null references tenants(id) on delete cascade,
          agent_id       text not null,
          name           text not null,
          ip             inet,
          os_platform    text,
          os_name        text,
          version        text,
          status         text,
          groups         text[] not null default '{}',
          last_keepalive timestamptz,
          synced_at      timestamptz not null default now(),
          primary key (tenant_id, agent_id)
        )
    """)

    # --- alerts: partitioned monthly on `timestamp` -------------------------
    op.execute("""
        create table alerts (
          id            uuid not null default gen_random_uuid(),
          tenant_id     uuid not null,
          wazuh_id      text not null,
          timestamp     timestamptz not null,
          received_at   timestamptz not null default now(),

          rule_id       integer not null,
          rule_level    smallint not null,
          rule_desc     text not null,
          rule_groups   text[] not null default '{}',
          mitre_ids     text[] not null default '{}',
          mitre_tactics text[] not null default '{}',

          agent_id      text,
          agent_name    text,

          ecs           jsonb not null,
          raw           jsonb not null,
          map_version   integer not null,

          related_ip    inet[] not null default '{}',
          related_user  text[] not null default '{}',
          related_host  text[] not null default '{}',
          related_hash  text[] not null default '{}',

          fingerprint   text not null,
          incident_id   uuid,

          primary key (id, timestamp),
          constraint alerts_tenant_wazuh_uq unique (tenant_id, wazuh_id, timestamp)
        ) partition by range (timestamp)
    """)
    op.execute("create index alerts_tenant_ts_idx on alerts (tenant_id, timestamp desc)")
    op.execute("create index alerts_tenant_incident_idx on alerts (tenant_id, incident_id)")
    op.execute(
        "create index alerts_tenant_rule_ts_idx on alerts (tenant_id, rule_id, timestamp desc)"
    )
    op.execute(
        "create index alerts_tenant_fp_ts_idx on alerts (tenant_id, fingerprint, timestamp desc)"
    )
    op.execute("create index alerts_related_ip_idx on alerts using gin (related_ip)")
    op.execute("create index alerts_related_user_idx on alerts using gin (related_user)")
    op.execute("create index alerts_related_host_idx on alerts using gin (related_host)")
    op.execute("create index alerts_related_hash_idx on alerts using gin (related_hash)")
    op.execute("create index alerts_ecs_idx on alerts using gin (ecs jsonb_path_ops)")

    op.execute("""
        create table incidents (
          id            uuid primary key default gen_random_uuid(),
          tenant_id     uuid not null references tenants(id) on delete cascade,
          number        bigint not null,
          title         text not null,
          status        text not null default 'new'
                          check (status in
                            ('new','active','pending','resolved','false_positive')),
          severity      smallint not null,
          classification text,
          assignee_id   uuid references users(id) on delete set null,

          fingerprint   text not null,
          first_seen    timestamptz not null,
          last_seen     timestamptz not null,
          alert_count   integer not null default 0,
          rule_summary  jsonb not null default '{}',
          evidence      jsonb not null default '{}',
          related_incident_id uuid references incidents(id) on delete set null,

          closed_at     timestamptz,
          created_at    timestamptz not null default now(),
          updated_at    timestamptz not null default now(),
          constraint incidents_tenant_number_uq unique (tenant_id, number)
        )
    """)
    op.execute(
        "create index incidents_tenant_status_idx on incidents (tenant_id, status, last_seen desc)"
    )
    # Cross-tenant staff queue.
    op.execute("create index incidents_status_idx on incidents (status, last_seen desc)")
    op.execute(
        "create index incidents_tenant_assignee_idx on incidents (tenant_id, assignee_id, status)"
    )
    # One open incident per fingerprint, as a database invariant rather than an
    # application hope.
    op.execute("""
        create unique index incidents_open_fingerprint_uq on incidents (tenant_id, fingerprint)
          where status in ('new','active','pending')
    """)

    op.execute("""
        create table entities (
          id          uuid primary key default gen_random_uuid(),
          tenant_id   uuid not null references tenants(id) on delete cascade,
          type        text not null check (type in
                        ('ip','user','host','hash','process','file')),
          value       text not null,
          first_seen  timestamptz not null,
          last_seen   timestamptz not null,
          alert_count integer not null default 0,
          notes       text,
          constraint entities_tenant_type_value_uq unique (tenant_id, type, value)
        )
    """)
    op.execute(
        "create index entities_tenant_type_idx on entities (tenant_id, type, last_seen desc)"
    )

    op.execute("""
        create table incident_entities (
          incident_id uuid not null references incidents(id) on delete cascade,
          entity_id   uuid not null references entities(id) on delete cascade,
          role        text,
          primary key (incident_id, entity_id)
        )
    """)

    op.execute("""
        create table incident_comments (
          id          uuid primary key default gen_random_uuid(),
          incident_id uuid not null references incidents(id) on delete cascade,
          user_id     uuid not null references users(id),
          body        text not null,
          visibility  text not null default 'internal'
                        check (visibility in ('internal','client')),
          created_at  timestamptz not null default now()
        )
    """)

    op.execute("""
        create table audit_log (
          id          bigserial primary key,
          tenant_id   uuid references tenants(id) on delete cascade,
          user_id     uuid references users(id),
          action      text not null,
          target_type text not null,
          target_id   uuid,
          detail      jsonb not null default '{}',
          created_at  timestamptz not null default now()
        )
    """)
    op.execute(
        "create index audit_log_tenant_created_idx on audit_log (tenant_id, created_at desc)"
    )
    op.execute(
        "create index audit_log_target_idx on audit_log (tenant_id, target_type, target_id)"
    )

    op.execute("""
        create table ingest_stats (
          tenant_id   uuid not null references tenants(id) on delete cascade,
          day         date not null,
          alert_count bigint not null default 0,
          bytes_in    bigint not null default 0,
          primary key (tenant_id, day)
        )
    """)

    # First partitions, so the very first ingest has somewhere to land. The
    # worker's daily maintenance keeps them rolling from here.
    op.execute("""
        do $do$
        declare
          start_month date := date_trunc('month', now())::date;
          i integer;
          s date;
          e date;
        begin
          for i in 0..3 loop
            s := start_month + (i || ' months')::interval;
            e := s + interval '1 month';
            execute format(
              'create table if not exists alerts_%s partition of alerts '
              'for values from (%L) to (%L)',
              to_char(s, 'YYYY_MM'), s, e
            );
          end loop;
        end
        $do$
    """)


def downgrade() -> None:
    for table in (
        "ingest_stats",
        "audit_log",
        "incident_comments",
        "incident_entities",
        "entities",
        "incidents",
        "alerts",
        "agents",
        "staff_tenant_access",
        "users",
        "wazuh_connections",
        "tenants",
    ):
        op.execute(f"drop table if exists {table} cascade")
